# Generated by Django 4.2.7 on 2023-12-06 06:22

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplication',
            name='photo_file2',
            field=models.ImageField(default=1, upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), app.models.validate_image_size], verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
