# Generated by Django 4.2.7 on 2023-12-06 06:24

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aplication_photo_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplication',
            name='photo_file2',
            field=models.ImageField(upload_to='photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), app.models.validate_image_size], verbose_name='Фото готовой заявки'),
        ),
    ]
