# Generated by Django 4.2.7 on 2023-12-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aplication_photo_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
